# https://github.com/elastic/elasticsearch-docker
FROM https://6j3mjczk.mirror.aliyuncs.com/elasticsearch/elasticsearch-oss:6.2.2

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
