# https://github.com/elastic/elasticsearch-docker
FROM registry.docker-cn.com/elasticsearch/elasticsearch-oss:6.2.2

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
