# https://github.com/elastic/logstash-docker
FROM https://6j3mjczk.mirror.aliyuncs.com/logstash/logstash-oss:6.2.2

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
