# https://github.com/elastic/logstash-docker
FROM registry.docker-cn.com/logstash/logstash-oss:6.2.2

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
